# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CityGuidesDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CityGuidesDemo
  pod 'rx-coordinator'
  # pod 'Hero'
  pod 'Action'
  pod 'RxDataSources', '~> 3.0'
  pod 'Moya/RxSwift', '~> 10.0.2'
end
